import type { FormField } from '@/types/builder.types';

export const mockFields: FormField[] = [
  {
    id: 'field-1',
    index: 0,
    sectionItem: 'section-2',
    type: 'short-text',
    label: 'What is your full name?',
    info: 'Please enter your legal name as it appears on your ID.',
    required: true,
    options: [],
    placeholder: 'Full name',
    validation: { minLength: 2, maxLength: 100, pattern: null },
    defaultValue: '',
    hidden: false,
  },
  {
    id: 'field-2',
    index: 1,
    sectionItem: 'section-3',
    type: 'dropdown',
    label: 'What is your age group?',
    info: null,
    required: true,
    options: ['Under 18', '18-24', '25-34', '35-44', '45-54', '55+'],
    placeholder: 'Select age group',
    validation: { minLength: null, maxLength: null, pattern: null },
    defaultValue: '',
    hidden: false,
  },
  {
    id: 'field-3',
    index: 2,
    sectionItem: 'section-5',
    type: 'checkbox',
    label: 'Which of the following do you use regularly?',
    info: 'Select all that apply.',
    required: false,
    options: ['Email', 'SMS', 'Phone Calls', 'Social Media'],
    placeholder: null,
    validation: { minLength: null, maxLength: null, pattern: null },
    defaultValue: '',
    hidden: false,
  },
  {
    id: 'field-4',
    index: 3,
    sectionItem: 'section-5',
    type: 'radio-group',
    label: 'What is your preferred contact method?',
    info: null,
    required: true,
    options: ['Email', 'SMS', 'Phone Call'],
    placeholder: null,
    validation: { minLength: null, maxLength: null, pattern: null },
    defaultValue: '',
    hidden: false,
  },
  {
    id: 'field-5',
    index: 4,
    sectionItem: 'section-5',
    type: 'date-picker',
    label: 'When did you last complete a survey?',
    info: null,
    required: false,
    options: [],
    placeholder: 'Select date',
    validation: { minLength: null, maxLength: null, pattern: null },
    defaultValue: '',
    hidden: false,
  },
  {
    id: 'field-6',
    index: 5,
    sectionItem: 'section-5',
    type: 'file-upload',
    label: 'Upload a profile picture (optional)',
    info: 'JPG, PNG, or GIF. Max 2MB.',
    required: false,
    options: [],
    placeholder: null,
    validation: { minLength: null, maxLength: null, pattern: null },
    defaultValue: '',
    hidden: false,
  },
  {
    id: 'field-7',
    index: 6,
    sectionItem: 'section-5',
    type: 'long-text',
    label: 'Tell us about yourself',
    info: 'You can write about your background, interests, or anything else.',
    required: false,
    options: [],
    placeholder: 'Your answer',
    validation: { minLength: 10, maxLength: 1000, pattern: null },
    defaultValue: '',
    hidden: false,
  },
];
