import type { FormField, SelectOption } from '@/types/builder.types';

const toSlug = (label: string) => label.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '');

export const mockFields: FormField[] = [
  {
    id: 'field-1',
    index: 0,
    sectionItem: 'section-2',
    type: 'short-text',
    label: 'What is your full name?',
    info: 'Please enter your legal name as it appears on your ID.',
    required: true,
    options: [],
    placeholder: 'Full name',
    validation: { minLength: 2, maxLength: 100, pattern: null },
    defaultValue: '',
    hidden: false,
  },
  {
    id: 'field-2',
    index: 1,
    sectionItem: 'section-3',
    type: 'dropdown',
    label: 'What is your age group?',
    info: null,
    required: true,
    options: [
      { label: 'Under 18', value: 'under_18' },
      { label: '18-24', value: '18_24' },
      { label: '25-34', value: '25_34' },
      { label: '35-44', value: '35_44' },
      { label: '45-54', value: '45_54' },
      { label: '55+', value: '55_plus' },
    ],
    placeholder: 'Select age group',
    validation: { minLength: null, maxLength: null, pattern: null },
    defaultValue: '',
    hidden: false,
  },
  {
    id: 'field-3',
    index: 2,
    sectionItem: 'section-5',
    type: 'checkbox',
    label: 'Which of the following do you use regularly?',
    info: 'Select all that apply.',
    required: false,
    options: [
      { label: 'Email', value: 'email' },
      { label: 'SMS', value: 'sms' },
      { label: 'Phone Calls', value: 'phone_calls' },
      { label: 'Social Media', value: 'social_media' },
    ],
    placeholder: null,
    validation: { minLength: null, maxLength: null, pattern: null },
    defaultValue: '',
    hidden: false,
  },
  {
    id: 'field-4',
    index: 3,
    sectionItem: 'section-5',
    type: 'radio-group',
    label: 'What is your preferred method of communication?',
    info: null,
    required: true,
    options: [
      { label: 'Email', value: 'email' },
      { label: 'SMS', value: 'sms' },
      { label: 'Phone Calls', value: 'phone_calls' },
    ],
    placeholder: null,
    validation: { minLength: null, maxLength: null, pattern: null },
    defaultValue: '',
    hidden: false,
  },
  {
    id: 'field-5',
    index: 4,
    sectionItem: 'section-5',
    type: 'date-picker',
    label: 'When is your birthday?',
    info: null,
    required: true,
    options: [],
    placeholder: 'Select date',
    validation: { minLength: null, maxLength: null, pattern: null },
    defaultValue: '',
    hidden: false,
  },
  {
    id: 'field-6',
    index: 3,
    sectionItem: 'section-10',
    type: 'short-text',
    label: 'What is your favorite hobby?',
    info: 'Share your favorite hobby or pastime.',
    required: false,
    options: [],
    placeholder: 'e.g. Reading, Hiking',
    validation: { minLength: 2, maxLength: 50, pattern: null },
    defaultValue: '',
    hidden: false,
  },
];
