import type { FormGroupItem } from '@/types/builder.types';

export const mockSectionItems: FormGroupItem[] = [
  {
    id: 'section-1',
    index: 0,
    formStep: 'step-1',
    type: 'element',
    hidden: false,
    targetID: 'element-1',
  },
  {
    id: 'section-2',
    index: 1,
    formStep: 'step-1',
    type: 'field',
    hidden: false,
    targetID: 'field-1',
  },
  {
    id: 'section-3',
    index: 2,
    formStep: 'step-1',
    type: 'field',
    hidden: false,
    targetID: 'field-2',
  },
  {
    id: 'section-4',
    index: 3,
    formStep: 'step-1',
    type: 'element',
    hidden: false,
    targetID: 'element-2',
  },
  {
    id: 'section-5',
    index: 4,
    formStep: 'step-1',
    type: 'field',
    hidden: false,
    targetID: 'field-3',
  },
  {
    id: 'section-6',
    index: 5,
    formStep: 'step-1',
    type: 'element',
    hidden: false,
    targetID: 'element-3',
  },
  {
    id: 'section-7',
    index: 0,
    formStep: 'step-2',
    type: 'element',
    hidden: false,
    targetID: 'element-6',
  },
  {
    id: 'section-8',
    index: 1,
    formStep: 'step-2',
    type: 'element',
    hidden: false,
    targetID: 'element-7',
  },
  {
    id: 'section-9',
    index: 2,
    formStep: 'step-2',
    type: 'element',
    hidden: false,
    targetID: 'element-8',
  },
  {
    id: 'section-10',
    index: 3,
    formStep: 'step-2',
    type: 'field',
    hidden: false,
    targetID: 'field-6',
  },
  {
    id: 'section-11',
    index: 4,
    formStep: 'step-2',
    type: 'element',
    hidden: false,
    targetID: 'element-9',
  },
];
